#!/bin/bash
INTERFACE="wlp2s0" # Cambia esto por tu interfaz (usa 'ip link' para verla)

# Leer bytes actuales
R1=$(cat /sys/class/net/$INTERFACE/statistics/rx_bytes)
T1=$(cat /sys/class/net/$INTERFACE/statistics/tx_bytes)
sleep 1
R2=$(cat /sys/class/net/$INTERFACE/statistics/rx_bytes)
T2=$(cat /sys/class/net/$INTERFACE/statistics/tx_bytes)

# Calcular velocidad (bytes por segundo)
TBPS=$((($T2-$T1) / 1024))
RBPS=$((($R2-$R1) / 1024))

echo "⬇${TBPS}K ⬆${TBPS}K"
